EventBridgeConfig:
  - region: "us-east-1"
    LambdaFunctionLayerARN : 'PythonRequests:1'
  # - region: "us-east-2"
  #   LambdaFunctionLayerARN : 'arn:aws:lambda:us-east-2:205631354229:layer:PythonRequestsLayer:1'
